### ISSUE TITLE
Wasabi::Resolver::HTTPError: Error: 403 for url

### ISSUE THREAD

**Issue by RomainFranklin** [lemonwaysas/ruby-client-directkit-string#2]
ruby 2.3.0
rails 4.2.5.2
gem lemonway 1.0.1
heroku

En production, erreur suivante :

client = Lemonway::Client.new(
  wsdl: 'https://ws.lemonway.fr/mb/[...]/prod/directkitjson/service.asmx?wsdl',
  wl_login: 'login',
  wl_pass: 'pwd',
  language: 'fr',
  version: '2.0'
)

client.operations =>

Wasabi::Resolver::HTTPError: Error: 403 for url https://ws.lemonway.fr/mb/[...]/prod/directkitjson/service.asmx?wsdl

la même manip fonctionne en environnement de dev avec l'url "https://ws.lemonway.fr/mb/[...]/dev/directkitjson/service.asmx?wsdl"

est-ce qu'il y a une config à faire sur Heroku, ou c'est autre chose ?

**Comment by pham-dat** [comment]
C'est parce que votre IP n'est pas whitelisté. Communiquez-nous votre IP en faisant un ticket.
[https://www.lemonway.fr/support/scp/tickets.php?id=14824](https://www.lemonway.fr/support/scp/tickets.php?id=14824)

**Comment by RomainFranklin** [comment]
Toujours pas résolu.

Ce n'est pas l'IP.

J'ai essayé d'utiliser le DirectkitXML https://ws.lemonway.fr/mb/[...]/prod/directkitxml/service.asmx?wsdl mais toujours la même erreur

**Comment by itkin** [comment]
avez vous utilisé un proxy pour avoir une ip fixe que vous avez fait whitelister par lemonway ? Il y a un add-on heroku pour cela .

ci joint  un exemple d'initialisation du client : 

``` ruby
Client = Lemonway::Client.new(config.fetch('client')) do |options|
  options.proxy ENV['PROXIMO_URL'] if ENV['PROXIMO_URL'].present?
  options.ssl_verify_mode(:none) unless Rails.env.production?
end
```

**Comment by RomainFranklin** [comment]
Non, je vais essayer, quel est le nom de l'add-on ?

MAJ Ok je teste proximo.

**Comment by itkin** [comment]
ya PROXIMO, mais regarde dans la liste des plugins

**Comment by RomainFranklin** [comment]
j'ai installé quotaguard, j'ai whitelisté les 2 IPs statiques fournies, mon client Lemon est bien initialisé avec le proxy mais toujours le même problème.

**Comment by itkin** [comment]
t'as mis l'option options.ssl_verify_mode(:none) ? t'as peut etre un pb de ssl ...

**Comment by RomainFranklin** [comment]
je ne vais pas désactiver le mode ssl en production.

**Comment by itkin** [comment]
a mon avis c'est la qu'il faut regarder (au niveau des certifs tout ca). Pas forcément les tiens mais aussi ceux de l'api lemonway, regarde la doc de savon sur lequel la gem est contruite
